"""Phase 1 benchmark: which PDF parser should we build the project on?

Run:
    .venv\\Scripts\\python.exe -m src.ingest.parse_bench
    .venv\\Scripts\\python.exe -m src.ingest.parse_bench --pages 12 --excerpt-chars 900

Produces reports/01_parsing_quality.md containing TWO things, because
neither alone is sufficient:

  1. A metrics table that RANKS the parsers.
  2. Side-by-side raw text excerpts, so a human can CONFIRM the ranking.

Step 2 is not decoration. Proxy metrics can be gamed by a parser that drops
content entirely (high alpha_ratio, low fragment ratio, terrible output).
Read the excerpts before trusting the table.

SAMPLING
--------
Pages are chosen deterministically — evenly spaced through the body, with
front and back matter skipped. No RNG, no seed to remember: re-running after
changing a metric produces a comparable table rather than a different sample.
Front matter is skipped because a title page extracts perfectly under every
parser and tells us nothing.
"""

from __future__ import annotations

import argparse
import sys
from collections import defaultdict
from pathlib import Path

import pandas as pd
from rich.console import Console

from .parsers import ALL_PARSERS, PageExtraction
from .quality import HIGHER_IS_BETTER, repeated_line_ratio, score_page
from .toc import summarize

console = Console()

RAW_DIR = Path("data/raw")
REPORT = Path("reports/01_parsing_quality.md")

# Fraction of the book treated as front/back matter and skipped.
FRONT_SKIP = 0.08
BACK_SKIP = 0.05


def sample_pages(n_pages: int, k: int) -> list[int]:
    """Evenly spaced page indices through the body of a document.

    >>> sample_pages(100, 4)
    [8, 29, 50, 71]
    >>> sample_pages(3, 5)
    [0, 1, 2]
    """
    lo = int(n_pages * FRONT_SKIP)
    hi = int(n_pages * (1 - BACK_SKIP))
    if hi - lo < k:
        return list(range(min(n_pages, max(k, 1))))[:n_pages]
    step = (hi - lo) // k
    return [lo + i * step for i in range(k)]


def bench_book(pdf: Path, k: int) -> tuple[pd.DataFrame, dict, dict]:
    """Benchmark every parser on one book.

    Returns (per-page metrics, per-parser aggregates, raw excerpts).
    """
    rows: list[dict] = []
    excerpts: dict[str, dict[int, str]] = defaultdict(dict)
    pages_by_parser: dict[str, list[str]] = defaultdict(list)
    toc_stats: dict[str, dict] = {}

    # Page count comes from PyMuPDF: it is the fastest, and if parsers
    # disagree on page count that is itself worth surfacing.
    try:
        n_pages = ALL_PARSERS["pymupdf"].page_count(pdf)
    except Exception as e:                                  # noqa: BLE001
        console.print(f"[red]cannot open {pdf.name}: {e}[/red]")
        return pd.DataFrame(), {}, {}

    targets = sample_pages(n_pages, k)
    console.print(f"[cyan]{pdf.name}[/cyan]  {n_pages} pages → sampling {targets}")

    for name, parser in ALL_PARSERS.items():
        for pno in targets:
            ex: PageExtraction = parser.extract_page(pdf, pno)
            pages_by_parser[name].append(ex.text)
            excerpts[name][pno] = ex.text

            if not ex.ok:
                console.print(f"  [red]{name} p{pno}: {ex.error}[/red]")
                continue

            q = score_page(name, pno, ex.text)
            rows.append(
                {
                    "book": pdf.stem[:28],
                    "parser": name,
                    "page": pno,
                    "chars_per_page": q.chars_per_page,
                    "alpha_ratio": q.alpha_ratio,
                    "single_char_token_ratio": q.single_char_token_ratio,
                    "broken_hyphen_rate": q.broken_hyphen_rate,
                    "ms": ex.elapsed_ms,
                }
            )

        # TOC recovery is scored separately: a parser can produce fine text
        # and still recover no structure at all.
        try:
            toc_stats[name] = summarize(parser.extract_toc(pdf))
        except Exception:                                   # noqa: BLE001
            toc_stats[name] = summarize([])

    # Per-document metric: needs all sampled pages together.
    doc_level = {
        name: repeated_line_ratio(texts) for name, texts in pages_by_parser.items()
    }

    return pd.DataFrame(rows), {"toc": toc_stats, "repeated": doc_level}, excerpts


def render_report(
    df: pd.DataFrame, extras: dict, excerpts: dict, excerpt_chars: int
) -> str:
    """Assemble the markdown report."""
    out: list[str] = [
        "# Phase 1 — PDF Parsing Quality",
        "",
        "> Generated by `src/ingest/parse_bench.py`. Metrics **rank** the parsers;",
        "> the excerpts at the bottom are how you **confirm** the ranking. Read both.",
        "",
        "## Metric directions",
        "",
        "| Metric | Better | Detects |",
        "|---|---|---|",
        "| `chars_per_page` | higher | text silently dropped |",
        "| `alpha_ratio` | higher | math/garbage soup |",
        "| `single_char_token_ratio` | lower | shattered equations |",
        "| `broken_hyphen_rate` | lower | words destroyed at line breaks |",
        "| `repeated_line_ratio` | lower | running headers/footers as noise |",
        "",
    ]

    if df.empty:
        out.append("**No data — no PDFs found in `data/raw/`.**")
        return "\n".join(out)

    metric_cols = [c for c in HIGHER_IS_BETTER if c in df.columns]

    out += ["## Overall — averaged across all books", ""]
    overall = df.groupby("parser")[metric_cols + ["ms"]].mean().round(4)
    out += [overall.to_markdown(), ""]

    out += ["## Per book", ""]
    for book, sub in df.groupby("book"):
        out += [f"### {book}", ""]
        out += [sub.groupby("parser")[metric_cols + ["ms"]].mean().round(4).to_markdown(), ""]

    out += ["## TOC recovery", "",
            "A parser recovering 0 entries from a book that has chapters has failed",
            "at something the text metrics cannot see.", ""]
    for book, stats in extras.items():
        out += [f"### {book}", "",
                "| Parser | Entries | Chapters | Sections | Max depth | Repeated-line ratio |",
                "|---|---|---|---|---|---|"]
        for parser, s in stats["toc"].items():
            rep = stats["repeated"].get(parser)
            rep_s = f"{rep:.3f}" if isinstance(rep, float) else "n/a"
            out.append(
                f"| {parser} | {s['total_entries']} | {s['chapters']} | "
                f"{s['sections']} | {s['max_depth']} | {rep_s} |"
            )
        out.append("")

    out += ["---", "", "## Raw excerpts — READ THESE", "",
            "Same page, every parser. Look for: shattered equations, glued headers,",
            "hyphen breaks, interleaved columns, missing ligatures.", ""]
    for book, per_parser in excerpts.items():
        out += [f"### {book}", ""]
        sample_pages_shown = sorted(next(iter(per_parser.values())).keys())[:2]
        for pno in sample_pages_shown:
            out += [f"#### page {pno}", ""]
            for parser, pages in per_parser.items():
                text = (pages.get(pno) or "").strip()[:excerpt_chars]
                out += [f"**{parser}**", "", "```text", text or "(empty)", "```", ""]

    out += ["---", "", "## Decision", "",
            "- **Chosen parser:** _TBD — fill in after reading the excerpts_",
            "- **Why:** _..._",
            "- Record in `plan.md` decision log as **D1**, and set",
            "  `corpus.parser` in `configs/experiment.yaml`, upgrading its tag to `[PROVEN]`.", ""]

    return "\n".join(out)


def main() -> int:
    ap = argparse.ArgumentParser(description="Benchmark PDF parsers (Phase 1).")
    ap.add_argument("--pages", type=int, default=8, help="pages sampled per book")
    ap.add_argument("--excerpt-chars", type=int, default=700)
    ap.add_argument("--raw-dir", type=Path, default=RAW_DIR)
    args = ap.parse_args()

    pdfs = sorted(args.raw_dir.glob("*.pdf"))
    if not pdfs:
        console.print(f"[red]No PDFs in {args.raw_dir}/[/red] — add the books first.")
        return 1

    frames, all_extras, all_excerpts = [], {}, {}
    for pdf in pdfs:
        df, extras, excerpts = bench_book(pdf, args.pages)
        if not df.empty:
            frames.append(df)
            all_extras[pdf.stem[:28]] = extras
            all_excerpts[pdf.stem[:28]] = excerpts

    combined = pd.concat(frames, ignore_index=True) if frames else pd.DataFrame()

    REPORT.parent.mkdir(parents=True, exist_ok=True)
    REPORT.write_text(
        render_report(combined, all_extras, all_excerpts, args.excerpt_chars),
        encoding="utf-8",
    )
    console.print(f"[green]wrote {REPORT}[/green]")

    if not combined.empty:
        cols = [c for c in HIGHER_IS_BETTER if c in combined.columns]
        console.print(combined.groupby("parser")[cols + ["ms"]].mean().round(4))

    return 0


if __name__ == "__main__":
    sys.exit(main())
